version: '3.8'

services:
  events-api:
    container_name: events_api
    depends_on:
      - openapi_mock
    build:
      context: ./events-api
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    environment:
      DEPLOYMENT_ENV: 'dev'
      LOG_LEVEL: 'DEBUG'
      API_KEY: 'SOME-RANDOM-KEY' # this should be injected at deployment in prod
      THIRD_PARTY_URL: 'http://openapi_mock:8080'
      SCOREBOARD_ENDPOINT: '/scoreboard'
      TEAM_RANKINGS_ENDPOINT: '/team-rankings'

  openapi_mock:
    container_name: openapi_mock
    image: muonsoft/openapi-mock
    volumes:
    - ./3rd-party-api:/etc/openapi
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/etc/openapi/openapi.yaml'
      OPENAPI_MOCK_USE_EXAMPLES: 'if_present'
    ports:
      - "9000:8080"